INSERT INTO `atya_nidan`.`Specialisation` (name, description) VALUES
('Endocrinologist', 'One who studies hormone disorders'),
('Dermatologist', 'One who specializes in skin disorders'),
('Cardiologist', 'One who specializes in heart disorders'),
('Neurologist', 'One who studies disorders of the nervous system'),
('Gynecologist', 'One who specializes in women''s reproductive health'),
('Pediatrician', 'One who provides medical care for infants, children, and adolescents'),
('Orthopedic Surgeon', 'One who specializes in musculoskeletal disorders and surgeries'),
('Psychiatrist', 'One who diagnoses and treats mental health disorders'),
('Oncologist', 'One who specializes in the treatment of cancer'),
('Urologist', 'One who deals with disorders of the urinary tract and male reproductive system'),
('Pulmonologist', 'One who specializes in respiratory disorders'),
('Rheumatologist', 'One who studies and treats autoimmune and inflammatory disorders'),
('Ophthalmologist', 'One who specializes in eye and vision care'),
('ENT Specialist', 'One who deals with disorders of the ear, nose, and throat'),
('Allergist/Immunologist', 'One who specializes in allergies and immune system disorders'),
('Gastroenterologist', 'One who treats disorders of the digestive system'),
('Nephrologist', 'One who specializes in kidney disorders and diseases'),
('Hematologist', 'One who studies and treats blood disorders'),
('Geriatrician', 'One who specializes in the health care of elderly people'),
('Anesthesiologist', 'One who administers anesthesia and monitors patients during surgery'),
('Intensivist', 'One who specializes in critical care medicine, typically in ICU settings'),
('Infectious Disease Specialist', 'One who diagnoses and treats infectious diseases'),
('Plastic Surgeon', 'One who specializes in reconstructive and cosmetic surgery'),
('Radiologist', 'One who interprets medical images and performs interventional procedures using imaging techniques'),
('Physiatrist', 'One who specializes in physical medicine and rehabilitation'),
('Pathologist', 'One who studies the causes and effects of diseases'),
('Medical Geneticist', 'One who specializes in genetic disorders and hereditary diseases');
