package com.atyanidan.util;

public class ApiConstants extends Constants {
    public static final String DOCTORS_BY_DISTRICTS_API = HEALTH_SERVICE_BASE_PATH + DOCTORS_BY_DISTRICTS;
    public static final String FIELDWORKERS_BY_DISTRICTS_API = HEALTH_SERVICE_BASE_PATH + FIELDWORKERS_BY_DISTRICTS;
    public static final String ADMINS_BY_STATES_API = HEALTH_SERVICE_BASE_PATH + ADMINS_BY_STATES;
    public static final String CREATE_FORM_API = FORM_SERVICE_BASE_PATH + CREATE_FORM;
    public static final String FOLLOW_UPS_OF_FIELDWORKER_API = HEALTH_SERVICE_BASE_PATH + FOLLOW_UPS_OF_FIELDWORKER;
    public static final String CREATE_PRESCRIPTION_API = HEALTH_SERVICE_BASE_PATH + CREATE_PRESCRIPTION;
    public static final String ADMIN_STATS_API = HEALTH_SERVICE_BASE_PATH + ADMIN_STATS;
}
